on: [push]

name: Lint, Test, Build

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: Build scheduler app release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release --all-features
